# Cappy Configuration
version: "0.0.0"

cappy:
  initialized_at: "2025-08-18T20:11:07.756Z"
  last_updated: "2025-08-18T20:11:07.756Z"

stack:
  source: ".cappy/stack.md"
  validated: false
  validated_at:


tasks:
  directory: "tasks"
  history_directory: "history"

instructions:
  directory: "instructions"
